---
title: "Factor Analysis"
author: "Pablo E. Gutiérrez-Fonseca"
date: "9/3/2021"
output:
  pdf_document: default
  html_document: default
---

```{r}

library(nFactors)
library(foreign)
library(Hmisc)
library(corrplot)
library(psych)

```

1. Paso numero 1, determinar los factores que tienen un eigen vector >1.  
Esto se conoce como la regla de Kaiser.

```{r}

ev1 = eigen(cor(new_channel2)) 
ev1$values


#2. variabilidad explicada por cada factor individual, la cual debe de superar el 10%, en este caso, se indican 5 factores 
raices=ev1$values
raicesPorc = round((raices/sum(raices))*100,2)
raicesPorc


```
Identificamos 4 factores con eigen >1.


```{r}
ap1 <- parallel(subject=nrow(new_channel2),var=ncol(new_channel2),
                rep=100, cent=.05)

nS1 <- nScree(x=ev1$values, aparallel=ap1$eigen$qevpea)

plotnScree(nS1) #con este parece que hay 4 factores, pero 2 optimos 

```


```{r}
fit <- factanal(new_channel2, 4, rotation="none") # #SIEMPRE SE RECHAZÓ LA HIPOTESIS ENTONCES NO FUNCIONÓ
fit 

#CAMBIAMOS DE 1 HASTA 4 PARA VER LOS RESULTADOS 

#1 FACTOR
f.solution <- fa(new_channel2, nfactors=1, rotate="oblimin", fm="wls")
fa.diagram(f.solution)

#2 FACTOR
f.solution <- fa(new_channel2, nfactors=2, rotate="oblimin", fm="wls")
fa.diagram(f.solution)
print(f.solution)

#3 FACTOR
f.solution <- fa(new_channel2, nfactors=3, rotate="oblimin", fm="wls")
fa.diagram(f.solution)

#4 FACTOR
f.solution <- fa(new_channel2, nfactors=4, rotate="oblimin", fm="wls")
fa.diagram(f.solution)



```

